[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/bin/notifications-server --api --xmtp-listener --listener-type=v3 --xmtp-listener-tls --xmtp-address=grpc.dev.xmtp.network:443 --apns-enabled"
healthcheckPath = "/readyz"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
