[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "/usr/local/bin/bridge-entrypoint --api --xmtp-listener --listener-type=v4 --xmtp-listener-tls --xmtp-address=grpc.dev.xmtp.network:443 --hytch-secure-vault --bridge-environment=dev --apns-mode=development --bridge-teen-conversation-mode=disabled"
healthcheckPath = "/readyz"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
drainingSeconds = 30
